CREATE TYPE education_value AS ENUM ('bachleor', 'master', 'doctorate');

CREATE TABLE JobIDTable (
	jobID INTEGER NOT NULL,
	table VARCHAR(60),
	PRIMARY KEY (jobID)
);

CREATE TABLE Industries (
  jobID INTEGER PRIMARY KEY NOT NULL,
  industry VARCHAR(60),
  jobID INTEGER FOREIGN KEY REFERENCES JobIDTable(jobID)
);

CREATE TABLE Education (
  jobID INTEGER PRIMARY KEY NOT NULL,
  degreeTitle VARCHAR(15),
  educationLevel VARCHAR(15),
  jobID INTEGER FOREIGN KEY REFERENCES JobIDTable(jobID)
);

CREATE TABLE Skills (
  jobID INTEGER PRIMARY KEY NOT NULL,
  skill VARCHAR(60),
  jobID INTEGER FOREIGN KEY REFERENCES JobIDTable(jobID)
);

CREATE TABLE Languages (
  jobID INTEGER PRIMARY KEY NOT NULL,
  language VARCHAR(15),
  jobID INTEGER FOREIGN KEY REFERENCES JobIDTable(jobID)
);

CREATE TABLE WebDeveloper (
	jobID INTEGER NOT NULL,
	seniority VARCHAR(60),
	yearsOfExperience INTEGER,
	PRIMARY KEY (jobID),
	FOREIGN KEY (jobID) REFERENCES JobIDTable(jobID)
); 
